// <auto-generated />
namespace TourHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class overrideConventionTourGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overrideConventionTourGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201908021123260_overrideConventionTourGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
